### PR TITLE
Fix so CLI bucket-prefix option is now respected

### LINKED ISSUE #13: Bucket prefix not respected
The cli option to set a bucket prefix is not being respected, so Moodle site identifier is always being used.

### PR DESCRIPTION
**Pull request by mattporritt**
Prior to this site identifier was always used. Closes #13

### CODE REVIEW

File: classes/provision.php [hunk 1]
```diff
@@ -97,7 +97,7 @@ public function __construct($keyid, $secret, $region, $bucketprefix) {
         $this->secret = $secret;
         $this->region = $region;
 
-        if ($this->bucketprefix == '') {
+        if ($bucketprefix == '') {
```
Comment (dmitriim) [inline classes/provision.php]: would be good to cover this case with the tests
